### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by webprofusion-chrisc** [kstrauss/HttpSysManager#1]
Hi, would it be possible to set the MIT license on this project?

 I've chatted with the author on twitter and this is considered the current official github repo, but until it has a license it's unlikely anyone would use it for anything.

Thanks!

**Comment by kstrauss** [comment]
I went back to the code project article, and looked to see what license he referred to. There it was the CPOL. I added a reference to that.  #f5276b8aa8180d071a08b8e708739171ce2248ba

**Comment by webprofusion-chrisc** [comment]
Thanks! I don't know that license very well but I'm sure it's a good start.
